---
- name: Deploy New Switch
  gather_facts: false
  connection: local
  hosts: all

  tasks:  
  - name: AOS8 >> check 443 open port
    wait_for:
      host: '{{ ansible_host }}'
      port: 443
      state: started
      delay: 0
      timeout: 1
    ignore_errors: true
    register: port_443_state
    when: device_os == 'aos8'
  - name: DEBUG >> port 443 state
    debug:
      msg : "{{ port_443_state }}"

  - name: AOS8 >> rest login, get return cookie
    uri:
      url: https://{{ ansible_host }}/auth/?username={{ ale_username }}&password={{ ale_password }}
      method: GET
      validate_certs: false
    register: login
    until: login.status == 200
    when: device_os == 'aos8'

  - name: DEBUG >> login
    debug:
      msg:  "{{login.cookies_string}}"

  - name: AOS8 >> System Name
    uri:
      url: https://{{ ansible_host }}/cli/aos/?&cmd=system+name+{{ system_name }}
      method: GET
      validate_certs: false
      return_content: true
      headers:
        Cookie: "{{ login['cookies_string'] }}"
        Accept: application/vnd.alcatellucentaos+json
    when: device_os == 'aos8'

  - name: AOS8 >> System Location
    uri:
      url: https://{{ ansible_host }}/cli/aos/?&cmd=system+location+{{ system_location }}
      method: GET
      validate_certs: false
      return_content: true
      headers:
        Cookie: "{{ login['cookies_string'] }}"
        Accept: application/vnd.alcatellucentaos+json
    when: device_os == 'aos8'    

  - name: AOS8 >> System Contact
    uri:
      url: https://{{ ansible_host }}/cli/aos/?&cmd=system+contact+{{ system_contact }}
      method: GET
      validate_certs: false
      return_content: true
      headers:
        Cookie: "{{ login['cookies_string'] }}"
        Accept: application/vnd.alcatellucentaos+json
    when: device_os == 'aos8'      

  - name: AOS8 >> Create VLAN
    uri:
      url: https://{{ ansible_host }}/cli/aos/?&cmd=vlan+1
      method: GET
      validate_certs: false
      return_content: true
      headers:
        Cookie: "{{ login['cookies_string'] }}"
        Accept: application/vnd.alcatellucentaos+json
    when: device_os == 'aos8'      

  - name: AOS8 >> Create VLAN
    uri:
      url: https://{{ ansible_host }}/cli/aos/?&cmd=vlan+2
      method: GET
      validate_certs: false
      return_content: true
      headers:
        Cookie: "{{ login['cookies_string'] }}"
        Accept: application/vnd.alcatellucentaos+json
    when: device_os == 'aos8'      

  - name: AOS8 >> Create VLAN
    uri:
      url: https://{{ ansible_host }}/cli/aos/?&cmd=vlan+3
      method: GET
      validate_certs: false
      return_content: true
      headers:
        Cookie: "{{ login['cookies_string'] }}"
        Accept: application/vnd.alcatellucentaos+json
    when: device_os == 'aos8'      

  - name: AOS8 >> Create VLAN
    uri:
      url: https://{{ ansible_host }}/cli/aos/?&cmd=vlan+4
      method: GET
      validate_certs: false
      return_content: true
      headers:
        Cookie: "{{ login['cookies_string'] }}"
        Accept: application/vnd.alcatellucentaos+json
    when: device_os == 'aos8'     

  - name: AOS8 >> Create VLAN
    uri:
      url: https://{{ ansible_host }}/cli/aos/?&cmd=vlan+5
      method: GET
      validate_certs: false
      return_content: true
      headers:
        Cookie: "{{ login['cookies_string'] }}"
        Accept: application/vnd.alcatellucentaos+json
    when: device_os == 'aos8'      

  - name: AOS8 >> Create VLAN
    uri:
      url: https://{{ ansible_host }}/cli/aos/?&cmd=vlan+6
      method: GET
      validate_certs: false
      return_content: true
      headers:
        Cookie: "{{ login['cookies_string'] }}"
        Accept: application/vnd.alcatellucentaos+json
    when: device_os == 'aos8'       

  - name: AOS8 >> Create VLAN
    uri:
      url: https://{{ ansible_host }}/cli/aos/?&cmd=vlan+7
      method: GET
      validate_certs: false
      return_content: true
      headers:
        Cookie: "{{ login['cookies_string'] }}"
        Accept: application/vnd.alcatellucentaos+json
    when: device_os == 'aos8'       

  - name: AOS8 >> Create VLAN
    uri:
      url: https://{{ ansible_host }}/cli/aos/?&cmd=vlan+8
      method: GET
      validate_certs: false
      return_content: true
      headers:
        Cookie: "{{ login['cookies_string'] }}"
        Accept: application/vnd.alcatellucentaos+json
    when: device_os == 'aos8'        

  - name: AOS8 >> Create VLAN
    uri:
      url: https://{{ ansible_host }}/cli/aos/?&cmd=vlan+9
      method: GET
      validate_certs: false
      return_content: true
      headers:
        Cookie: "{{ login['cookies_string'] }}"
        Accept: application/vnd.alcatellucentaos+json
    when: device_os == 'aos8' 

  - name: AOS8 >> Create VLAN
    uri:
      url: https://{{ ansible_host }}/cli/aos/?&cmd=vlan+10
      method: GET
      validate_certs: false
      return_content: true
      headers:
        Cookie: "{{ login['cookies_string'] }}"
        Accept: application/vnd.alcatellucentaos+json
    when: device_os == 'aos8'     

  - name: AOS8 >> rest logout
    uri:
      url: https://{{ ansible_host }}/auth/?
      method: POST
      validate_certs: false
      status_code: 200
      headers:
        Cookies: "{{ login['cookies_string'] }}"
    when: device_os == 'aos8'